//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagmentService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public int UserID { get; set; }
        public int RoomID { get; set; }
        public int RoomServiceID { get; set; }
        public System.DateTime DateCheckIN { get; set; }
        public System.DateTime DateCheckOUT { get; set; }
        public float Price { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual RoomService RoomService { get; set; }
        public virtual User User { get; set; }
    }
}
