//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagmentService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string UniqueID { get; set; }
        public string Adress { get; set; }
        public string Sex { get; set; }
        public System.DateTime DateOfBird { get; set; }
        public string Email { get; set; }
        public string State { get; set; }
        public string Number { get; set; }
        public int PostCode { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
