//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomService
    {
        public RoomService()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int RoomServiceId { get; set; }
        public bool Breakfast { get; set; }
        public bool Lunch { get; set; }
        public bool Dinner { get; set; }
        public bool CleaningService { get; set; }
        public bool SpecialService { get; set; }
        public bool ServiceDone { get; set; }
    
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
