//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagment.HotelServiceFinal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelServiceFinal.HotelServisInterface")]
    public interface HotelServisInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelServisInterface/GetReservations", ReplyAction="http://tempuri.org/HotelServisInterface/GetReservationsResponse")]
        HotelService.Model.HotelReservation[] GetReservations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelServisInterface/GetReservations", ReplyAction="http://tempuri.org/HotelServisInterface/GetReservationsResponse")]
        System.Threading.Tasks.Task<HotelService.Model.HotelReservation[]> GetReservationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelServisInterface/ListHotelGuest", ReplyAction="http://tempuri.org/HotelServisInterface/ListHotelGuestResponse")]
        HotelService.Model.HotelUser[] ListHotelGuest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelServisInterface/ListHotelGuest", ReplyAction="http://tempuri.org/HotelServisInterface/ListHotelGuestResponse")]
        System.Threading.Tasks.Task<HotelService.Model.HotelUser[]> ListHotelGuestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelServisInterface/ListHotelRooms", ReplyAction="http://tempuri.org/HotelServisInterface/ListHotelRoomsResponse")]
        HotelService.Model.HotelRoom[] ListHotelRooms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelServisInterface/ListHotelRooms", ReplyAction="http://tempuri.org/HotelServisInterface/ListHotelRoomsResponse")]
        System.Threading.Tasks.Task<HotelService.Model.HotelRoom[]> ListHotelRoomsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelServisInterface/CheckLoginUser", ReplyAction="http://tempuri.org/HotelServisInterface/CheckLoginUserResponse")]
        HotelService.Model.HotelUser CheckLoginUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HotelServisInterface/CheckLoginUser", ReplyAction="http://tempuri.org/HotelServisInterface/CheckLoginUserResponse")]
        System.Threading.Tasks.Task<HotelService.Model.HotelUser> CheckLoginUserAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelServisInterfaceChannel : HotelManagment.HotelServiceFinal.HotelServisInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelServisInterfaceClient : System.ServiceModel.ClientBase<HotelManagment.HotelServiceFinal.HotelServisInterface>, HotelManagment.HotelServiceFinal.HotelServisInterface {
        
        public HotelServisInterfaceClient() {
        }
        
        public HotelServisInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelServisInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServisInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServisInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelService.Model.HotelReservation[] GetReservations() {
            return base.Channel.GetReservations();
        }
        
        public System.Threading.Tasks.Task<HotelService.Model.HotelReservation[]> GetReservationsAsync() {
            return base.Channel.GetReservationsAsync();
        }
        
        public HotelService.Model.HotelUser[] ListHotelGuest() {
            return base.Channel.ListHotelGuest();
        }
        
        public System.Threading.Tasks.Task<HotelService.Model.HotelUser[]> ListHotelGuestAsync() {
            return base.Channel.ListHotelGuestAsync();
        }
        
        public HotelService.Model.HotelRoom[] ListHotelRooms() {
            return base.Channel.ListHotelRooms();
        }
        
        public System.Threading.Tasks.Task<HotelService.Model.HotelRoom[]> ListHotelRoomsAsync() {
            return base.Channel.ListHotelRoomsAsync();
        }
        
        public HotelService.Model.HotelUser CheckLoginUser(string username, string password) {
            return base.Channel.CheckLoginUser(username, password);
        }
        
        public System.Threading.Tasks.Task<HotelService.Model.HotelUser> CheckLoginUserAsync(string username, string password) {
            return base.Channel.CheckLoginUserAsync(username, password);
        }
    }
}
